### PR TITLE
Fix relative schema urls

### LINKED ISSUE #983: Are relative URLs still supported?
I upgraded Huma from 2.35 to 2.37, but now my relative URLs are being replaced.

Here is my config:

```go
cfg := huma.DefaultConfig("My API", "1.0.0")
cfg.Servers = []*huma.Server{
	{URL: "/v1", Description: "Relative Path Server"},
}
```

But when I dump the API to JSON:

```go
api.OpenAPI().MarshalJSON()
```

I now see a diff where all of my relative URLs are being replaced:

```diff
--- a/openapi.json
+++ b/openapi.json
@@ -7,7 +7,7 @@
           "$schema": {
             "description": "A URL to the JSON Schema for this object.",
             "examples": [
-              "/v1/schemas/APIResponseOutput.json"
+              "https://example.com/schemas/APIResponseOutput.json"
             ],
             "format": "uri",
             "readOnly": true,
```

Is this expected behavior? Thanks!

### PR DESCRIPTION
**Pull request by wolveix**
Fixes #983.

There's an ongoing discussion in that issue regarding my suggestion to always use absolute URLs rather than relative URLs for the generated `$schema` field.

Would appreciate additional input, particularly from @danielgtaylor and @leonklingele :)

### CODE REVIEW

File: api.go [hunk 1]
```diff
@@ -405,12 +405,24 @@ func (a *api) Middlewares() Middlewares {
...
-			if u.Scheme != "" || strings.HasPrefix(server.URL, "/") {
-				return u.Path
-			}
+		if server.URL == "" {
+			continue
+		}
+
+		serverURL, err := url.Parse(server.URL)
+		if err != nil {
+			continue
```
Comment (leonklingele) [inline api.go]: Should we panic here?

**Review by leonklingele — APPROVED** [review]
Small nit, otherwise lgtm! 🚀
